import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import Providers from "./providers";
import Header from "@/components/header";
const inter = Inter({ subsets: ["latin"] });
import "animate.css";
import AosInit from "@/components/aosInit";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en" suppressHydrationWarning>
         <body className={inter.className}>
            <div className="overflow-x-hidden">
               <Providers>
                  <Header />
                  <Navbar />
                  {children}
                  <Footer />
                  <AosInit />
               </Providers>
            </div>
         </body>
      </html>
   );
}
